import { actorSeeds } from './actors.seed';

export const movieSeeds = [
  { title: 'Inception', actors: [actorSeeds[0], actorSeeds[6], actorSeeds[10]] },
  { title: 'The Devil Wears Prada', actors: [actorSeeds[1], actorSeeds[23], actorSeeds[45]] },
  { title: 'Forrest Gump', actors: [actorSeeds[2], actorSeeds[5], actorSeeds[41]] },
  { title: 'Training Day', actors: [actorSeeds[3], actorSeeds[19], actorSeeds[40]] },
  { title: 'Blue Jasmine', actors: [actorSeeds[4], actorSeeds[31], actorSeeds[38]] },
  { title: 'The Shawshank Redemption', actors: [actorSeeds[5], actorSeeds[41], actorSeeds[47]] },
  { title: 'Fight Club', actors: [actorSeeds[6], actorSeeds[8], actorSeeds[11]] },
  { title: 'Black Swan', actors: [actorSeeds[7], actorSeeds[25], actorSeeds[33]] },
  { title: 'Taxi Driver', actors: [actorSeeds[8], actorSeeds[45], actorSeeds[44]] },
  { title: 'Lost in Translation', actors: [actorSeeds[9], actorSeeds[35], actorSeeds[48]] },
  { title: 'The Dark Knight', actors: [actorSeeds[10], actorSeeds[6], actorSeeds[42]] },
  { title: 'Titanic', actors: [actorSeeds[0], actorSeeds[11], actorSeeds[45]] },
  { title: 'Joker', actors: [actorSeeds[12], actorSeeds[41], actorSeeds[42]] },
  { title: 'Fences', actors: [actorSeeds[13], actorSeeds[3], actorSeeds[36]] },
  { title: 'The Martian', actors: [actorSeeds[14], actorSeeds[37], actorSeeds[27]] },
  { title: 'La La Land', actors: [actorSeeds[15], actorSeeds[26], actorSeeds[39]] },
  { title: 'Ali', actors: [actorSeeds[16], actorSeeds[3], actorSeeds[41]] },
  { title: 'Moulin Rouge!', actors: [actorSeeds[17], actorSeeds[31], actorSeeds[45]] },
  { title: 'Pulp Fiction', actors: [actorSeeds[18], actorSeeds[19], actorSeeds[41]] },
  { title: 'Monster', actors: [actorSeeds[19], actorSeeds[31], actorSeeds[45]] },
  { title: 'The Silence of the Lambs', actors: [actorSeeds[20], actorSeeds[31], actorSeeds[45]] },
  { title: 'Arrival', actors: [actorSeeds[21], actorSeeds[37], actorSeeds[44]] },
  { title: 'Thor', actors: [actorSeeds[22], actorSeeds[37], actorSeeds[41]] },
  { title: 'Silver Linings Playbook', actors: [actorSeeds[23], actorSeeds[26], actorSeeds[29]] },
  { title: 'Beasts of No Nation', actors: [actorSeeds[24], actorSeeds[34], actorSeeds[45]] },
  { title: 'Les Misérables', actors: [actorSeeds[25], actorSeeds[31], actorSeeds[45]] },
  { title: 'Blade Runner 2049', actors: [actorSeeds[26], actorSeeds[35], actorSeeds[45]] },
  { title: 'Zero Dark Thirty', actors: [actorSeeds[27], actorSeeds[31], actorSeeds[45]] },
  { title: 'The Greatest Showman', actors: [actorSeeds[28], actorSeeds[37], actorSeeds[45]] },
  { title: 'Spotlight', actors: [actorSeeds[29], actorSeeds[31], actorSeeds[45]] },
  { title: 'There Will Be Blood', actors: [actorSeeds[30], actorSeeds[31], actorSeeds[45]] },
  { title: 'The Queen', actors: [actorSeeds[31], actorSeeds[37], actorSeeds[45]] },
  { title: 'No Country for Old Men', actors: [actorSeeds[32], actorSeeds[31], actorSeeds[45]] },
  { title: 'Snowpiercer', actors: [actorSeeds[33], actorSeeds[37], actorSeeds[45]] },
  { title: 'Moonlight', actors: [actorSeeds[34], actorSeeds[37], actorSeeds[45]] },
  { title: 'Three Billboards Outside Ebbing, Missouri', actors: [actorSeeds[35], actorSeeds[37], actorSeeds[45]] },
  { title: 'Sicario', actors: [actorSeeds[36], actorSeeds[37], actorSeeds[45]] },
  { title: 'A Quiet Place', actors: [actorSeeds[37], actorSeeds[37], actorSeeds[45]] },
  { title: 'The Theory of Everything', actors: [actorSeeds[38], actorSeeds[37], actorSeeds[45]] },
  { title: 'Hidden Figures', actors: [actorSeeds[39], actorSeeds[37], actorSeeds[45]] },
  { title: 'The Last King of Scotland', actors: [actorSeeds[40], actorSeeds[37], actorSeeds[45]] },
  { title: 'Frida', actors: [actorSeeds[41], actorSeeds[37], actorSeeds[45]] },
  { title: 'Shutter Island', actors: [actorSeeds[0], actorSeeds[6], actorSeeds[10]] },
  { title: '12 Years a Slave', actors: [actorSeeds[34], actorSeeds[37], actorSeeds[45]] },
  { title: 'Darkest Hour', actors: [actorSeeds[43], actorSeeds[37], actorSeeds[45]] },
  { title: 'The Impossible', actors: [actorSeeds[44], actorSeeds[37], actorSeeds[45]] },
  { title: 'Steve Jobs', actors: [actorSeeds[45], actorSeeds[37], actorSeeds[45]] },
  { title: 'Gone Girl', actors: [actorSeeds[46], actorSeeds[37], actorSeeds[45]] },
  { title: 'True Grit', actors: [actorSeeds[47], actorSeeds[37], actorSeeds[45]] },
  { title: 'Lady Bird', actors: [actorSeeds[48], actorSeeds[37], actorSeeds[45]] },
];
